### ISSUE TITLE
openvla version

### ISSUE THREAD

**Issue by phamhe** [Robot-VLAs/RoboVLMs#3]
Hello， great work！Thanks very match for open source this work！
I found several key-args mismatch for openvla dataset process，Is your work use the open source openvla? I use the latest version by btw
look forward for your response

**Comment by phamhe** [comment]
> Hello， great work！Thanks very match for open source this work！ I found several key-args mismatch for openvla dataset process，Is your work use the open source openvla? I use the latest version by btw look forward for your response

the mis-match key-args are mainly in traj_transform_kwargs，incluing  chunk_action, frame_num, left_pad, window_sample && filter_langs

**Comment by phamhe** [comment]
I found the issue has been fixed， thanks very much

**Comment by Ericonaldo** [comment]
Yes, sorry we forgot to mention that we use a fork version of openla
